server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shinyay/spring-cloud-config-gs.git
          clone-on-start: true
          search-paths: repos/
          skip-ssl-validation: true