spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: loadbalancer_1
          uri: lb://loadbalancer
          predicates:
            - Path=/myapp/**
            - Weight=group1, 4
          filters:
            - RewritePath=/myapp/(?<path>.*), $\/myapp
        - id: loadbalancer_2
          uri: lb://loadbalancer
          predicates:
            - Path=/myapp/**
            - Weight=group1, 3
          filters:
            - RewritePath=/myapp/(?<path>.*), $\/myapp2
        - id: loadbalancer_3
          uri: lb://loadbalancer
          predicates:
            - Path=/myapp/**
            - Weight=group1, 3
          filters:
            - RewritePath=/myapp/(?<path>.*), $\/myapp3